# Using Debian as a base
FROM debian:stable-slim
RUN apt-get update && apt-get install -y locales curl git zip unzip sudo netbase \
&& rm -rf /var/lib/apt/lists/* \
&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
&& useradd -m -d /app -s /bin/bash -g root -G sudo -p "$(openssl passwd -1 herc)" herc
ENV LANG en_US.utf8
USER herc
RUN mkdir -p /app/hercules
WORKDIR /app
RUN git clone https://github.com/wrljet/hercules-helper.git
COPY 	herc4.conf \
	buildHercules.sh \
	/app/
WORKDIR /app/hercules
ENTRYPOINT ["/bin/bash","-i","/app/buildHercules.sh"]
