# Using Debian as a base
FROM debian:stable-slim
RUN apt-get update && apt-get install -y cmake make regina-rexx libregina3-dev sudo wget time ncat build-essential autoconf automake flex gawk m4 libltdl-dev libtool-bin libcap2-bin libbz2-dev zlib1g-dev locales curl git zip unzip sudo netbase \
&& rm -rf /var/lib/apt/lists/* \
&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
&& useradd -m -d /app -s /bin/bash -g root -G sudo -p "$(openssl passwd -1 herc)" herc \
&& echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
ENV LANG=en_US.utf8
USER herc
RUN mkdir -p /app/hercules
WORKDIR /app
RUN git clone https://github.com/wrljet/hercules-helper.git
COPY herc4.conf \
	buildHercules.sh \
	/app/
WORKDIR /app/hercules
RUN /app/hercules-helper/hercules-buildall.sh --auto --flavor=sdl-hyperion --config=/app/herc4.conf \
&& /app/hercules/herc4x/hyperion-init-bash.sh \
WORKDIR /app
RUN rm -rf hercules-helper
WORKDIR /app/hercules
RUN zip -r /app/herc4x.zip herc4x
ENTRYPOINT ["/bin/bash","-i"]
