# Using Debian as a base
FROM debian:stable-slim
RUN apt-get update && apt-get install -y locales curl unzip c3270 netbase \
&& rm -rf /var/lib/apt/lists/* \
&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
&& mkdir -p /app/mvs
ENV LANG en_US.utf8

# Setup MVS
WORKDIR /app/mvs
RUN curl -O https://www.prince-webdesign.nl/images/downloads/mvs-tk5.zip \
&& unzip mvs-tk5.zip -d /app/mvs \
&& rm mvs-tk5.zip \
&& mv ./mvs-tk5/* -t /app/mvs \
&& chmod -R +x /app/mvs*
ADD mvs_docker /app/mvs/mvs_docker
ENTRYPOINT ["/bin/bash","./mvs_docker"]
