# Using Debian as a base
FROM debian:stable-slim
RUN apt-get update && apt-get install -y rsync locales curl unzip c3270 netbase \
&& rm -rf /var/lib/apt/lists/* \
&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
&& mkdir -p /app/mvs/backup
ENV LANG=en_US.utf8 \
PATH="/app/hercules/herc4x/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Setup MVS
WORKDIR /app/mvs
EXPOSE 3270 8080 3221 3223 3505 3506 8888
COPY mvs_docker \
	mvs-tk5.zip \
	tn3270 \
	herc4x.zip \
	zel3270 \
	zellij \
	herclogo.txt \
	/app/mvs/
COPY tk53270.kdl /app/mvs/3270.kdl
RUN chmod +x mvs-tk5.zip \
&& unzip mvs-tk5.zip \
&& rm mvs-tk5.zip \
&& mv ./mvs-tk5/* -t /app/mvs/backup \
&& rm -rf /app/mvs/backup/hercules/linux/64 \
&& unzip herc4x.zip -d /app/mvs/backup/hercules/linux/ \
&& rm herc4x.zip \
&& mv /app/mvs/backup/hercules/linux/herc4x /app/mvs/backup/hercules/linux/64 \
&& chmod -R +x /app/*
ENTRYPOINT ["/bin/bash","./mvs_docker"]
