# Using Debian as a base
FROM debian:stable-slim
RUN apt-get update && apt-get install -y rsync locales curl unzip c3270 netbase \
&& rm -rf /var/lib/apt/lists/* \
&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
&& mkdir -p /app/mvs/backup
ENV LANG=en_US.utf8 \
PATH="/app/hercules/herc4x/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

COPY --from=mhardingdk/mvs:herc4x /app/herc4x.zip /app/mvs/herc4x.zip

# Setup MVS
WORKDIR /app/mvs
EXPOSE 3270 8080 3221 3223 3505 3506 8888
COPY mvs_docker \
	tn3270 \
	zel3270 \
	zellij \
	herclogo.txt \
	/app/mvs/
COPY tk43270.kdl /app/mvs/3270.kdl
RUN curl -k -O https://wotho.pebble-beach.ch/tk4-/tk4-_v1.00_current.zip \
&& chmod +x tk4-_v1.00_current.zip \
&& unzip tk4-_v1.00_current.zip -d /app/mvs/backup \
&& rm tk4-_v1.00_current.zip \
&& rm -rf /app/mvs/backup/hercules/linux/64 \
&& unzip herc4x.zip -d /app/mvs/backup/hercules/linux/ \
&& mv /app/mvs/backup/hercules/linux/herc4x /app/mvs/backup/hercules/linux/64 \
&& rm herc4x.zip \
&& mkdir unattended \
&& chmod -R +x /app/*
ENTRYPOINT ["/bin/bash","./mvs_docker"]
