# Build MVSCE with c3270 and start of mvs in console mode
FROM mainframed767/mvsce:2.0.2
USER root

# Setup MVS
WORKDIR /
COPY hercules.zip herc4x.zip mvs.sh tn3270 /
RUN apt-get update && apt-get -yq install --no-install-recommends c3270 unzip \
&& apt-get clean \
&& chmod +x /mvs.sh \
&& chmod +x /tn3270 \
&& mkdir app \
&& unzip herc4x.zip \
&& rm herc4x.zip \
&& rm -rf /home/hercules/herctest/herc4x \
&& /app/hercules/herc4x/hyperion-init-bash.sh \
&& chmod -R +x /app/hercules/*
ENV PATH="/app/hercules/herc4x/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENTRYPOINT ["/bin/bash"]
